---
abstract: 'Simple Redis Rest Interface'
author:
  - 'Thiago Rondon <thiago@nsms.com.br>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Test::Mock::Redis: 0
  Test::Mojo: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ReRe
requires:
  Config::General: 0
  Mojolicious::Lite: 0
  Mojolicious::Plugin::BasicAuth: 0.02
  Moose: 0
  Redis: 0
resources:
  bugtracker: http://github.com/maluco/ReRe/issues
  repository: git://github.com/maluco/ReRe.git
version: 0.005
